# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    
    - name: Create virtual env
      run: |
        pip install virtualenv
        virtualenv --python=3.8 zappa-deploy-env
        source zappa-deploy-env/bin/activate
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Check credential
      run: |
        sudo aws configure list-profiles

    - name: Install Dependencies
      run: |
        source zappa-deploy-env/bin/activate
        python -m pip install --upgrade pip
        pip install django

    - name: Deploy with zappa
      env:
        VIRTUAL_ENV: ./zappa-deploy-env
      run: |
        source zappa-deploy-env/bin/activate
        pip install zappa
        zappa init
        zappa deploy dev
